

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=your-rds-host
      - DB_USER=your-db-user
      - DB_PASSWORD=your-db-password
      - DB_NAME=crm_app
      - PORT=3001

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
